SET LINESIZE 200
SET PAGESIZE 1000
SET TRIMSPOOL ON
SET TRIMOUT ON
SET FEEDBACK OFF
SET UNDERLINE " "
COLUMN id FORMAT 99
COLUMN name FORMAT A15
COLUMN email FORMAT A30
COLUMN password_hash FORMAT A60
