SET LINESIZE 200
SET PAGESIZE 1000
SET TRIMSPOOL ON
SET TRIMOUT ON
SET FEEDBACK OFF
SET UNDERLINE " "
COLUMN id FORMAT 99
COLUMN name FORMAT A15
COLUMN email FORMAT A30
COLUMN password_hash FORMAT A60



-- project

SET PAGESIZE 100
SET LINESIZE 200

COLUMN project_id FORMAT 9999
COLUMN project_name FORMAT A20
COLUMN description FORMAT A30
COLUMN created_by FORMAT 9999

-- task

COLUMN task_id     FORMAT 9999
COLUMN project_id  FORMAT 9999
COLUMN task_name   FORMAT A30
COLUMN status      FORMAT A15
COLUMN assigned_to FORMAT A10

